version: '3'
services:
    gitlab:
        image: gitlab/gitlab-ce:latest
        restart: always
        container_name: gitlab-ce
        ports:
        - "30080:30080"
        - "30022:22"
        environment:
           GITLAB_OMNIBUS_CONFIG: "external_url 'http://fedora-builder.local.dc:30080'; gitlab_rails['gitlab_shell_ssh_port']=30022;"
        volumes:
        - gitlab-ce-config:/etc/gitlab:Z
        - gitlab-ce-logs:/etc/gitlab:Z
        - gitlab-ce-data:/etc/gitlab:Z

        #- /srv/gitlab/config:/etc/gitlab:Z
        #- /srv/gitlab/logs:/var/log/gitlab:Z
        #- /srv/gitlab/data:/var/opt/gitlab:Z
    gitlab-runner:
        image: gitlab/gitlab-runner:latest
        restart: always
        container_name: gitlab-runner
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock:Z
        - gitlab-runner-config:/etc/gitlab-runner:Z

volumes:
    gitlab-ce-config:
        driver: local
    gitlab-ce-logs:
        driver: local
    gitlab-ce-data:
        driver: local
    gitlab-runner-config:
        driver: local
